# Generated by Django 5.0.6 on 2024-07-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_p_email_booking_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='patient_email',
            new_name='p_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_phone',
            new_name='p_phone',
        ),
    ]
